version: '2'
services:
  nginx:
    image: nginx:1.13
    container_name: lanve_nginx
    ports:
      - "80:8000"
    tty: true
    volumes:
      - ./nginx/conf/lanve_nginx_production.conf:/etc/nginx/conf.d/lanve_nginx_production.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./django/project/media:/media
      - ./django/project/static:/static
      - ./nginx/log:/var/log/nginx
    command: bash -c "cd / && mkdir -p var/www/letsencrypt"
    depends_on:
      - web
  db:
    image: mariadb:10.5
    container_name: lanve_mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    restart: always
    tty: true
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  web:
    build: ./web
    image: lanve_web
    container_name: lanve_web
    ports:
    - "8001:8001"
    restart: always
    tty: true
    command: uwsgi --ini /code/project/project/uwsgi.ini
    volumes:
      - ./django:/code
      - ./web/requirements.txt:/code/project/project/requirements.txt
    links:
      - db