# Generated by Django 3.0.1 on 2020-01-07 11:04

from django.db import migrations, models
import lanve.models


class Migration(migrations.Migration):

    dependencies = [
        ('lanve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanveuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default=lanve.models.get_default_profile_picture, upload_to=lanve.models.profile_pic_directory_path, verbose_name='profile pic'),
        ),
    ]
