# Generated by Django 3.0.1 on 2020-01-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanve', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='relationship',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
