# Generated by Django 3.0.1 on 2019-12-25 17:39

from django.db import migrations, models
import lanve.models


class Migration(migrations.Migration):

    dependencies = [
        ('lanve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanveuser',
            name='profile_pic',
            field=models.ImageField(blank=True, height_field=300, upload_to=lanve.models.profile_pic_directory_path, verbose_name='profile pic', width_field=300),
        ),
    ]
