# Generated by Django 3.0.1 on 2020-01-08 15:34

from django.db import migrations
import lanve.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('lanve', '0002_auto_20200107_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanveuser',
            name='profile_pic',
            field=stdimage.models.StdImageField(blank=True, default=lanve.models.get_default_profile_picture, upload_to=lanve.models.profile_pic_directory_path, verbose_name='profile picture'),
        ),
    ]
