# Generated by Django 3.0.1 on 2019-12-26 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lanve.models


class Migration(migrations.Migration):

    dependencies = [
        ('lanve', '0002_auto_20191226_0704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationship',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='relationship',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='IssueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question sentence')),
                ('situation', models.TextField(blank=True, verbose_name='situation')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contributor', models.ForeignKey(on_delete=models.SET(lanve.models.set_default_contributor_issue_name), related_name='contributor_issue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='comment')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('contributor', models.ForeignKey(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, related_name='contributor_comment', to=settings.AUTH_USER_MODEL, verbose_name='contributor')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='lanve.IssueModel', verbose_name='issue')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
