# Generated by Django 3.0.1 on 2019-12-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanve', '0003_auto_20191225_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lanveuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
    ]
