# Generated by Django 3.0.1 on 2020-01-13 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lanve', '0003_auto_20200108_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanveuser',
            name='answer_num',
        ),
        migrations.RemoveField(
            model_name='lanveuser',
            name='bad',
        ),
        migrations.RemoveField(
            model_name='lanveuser',
            name='good',
        ),
        migrations.RemoveField(
            model_name='lanveuser',
            name='helpful',
        ),
        migrations.RemoveField(
            model_name='lanveuser',
            name='not_helpful',
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=50, verbose_name='IP Address')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_comment', to='lanve.Comment')),
            ],
        ),
    ]
