# Generated by Django 3.0.1 on 2019-12-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lanve', '0003_auto_20191226_0834'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueModel',
            new_name='Issue',
        ),
    ]
