# Generated by Django 3.0.1 on 2020-01-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lanve', '0005_auto_20200114_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanveuser',
            name='count_view',
            field=models.PositiveIntegerField(default=0, verbose_name='the number of this issue view'),
        ),
    ]
